using DaggerSDK.Introspection;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace DaggerSDK;

static class API
{
	public static CompilationUnitSyntax Generate(Schema schema)
		=> CompilationUnit()
			.AddComment("This file was auto-generated by DaggerSDKCodeGen\n// Do not make direct changes to this file.")
			.AddUsings
			(
				"System.Collections.Immutable",
				"System.Text.Json",
				"System.Text.Json.Serialization"
			)
			.AddUsingStatic("DaggerSDK", "APIUtils")
			.WithFileScopedNamespaceDeclaration("DaggerSDK")
			.AddMembers
			(
				Structures.Generate(schema)
					.Concat(Classes.Generate(schema))
			);
}
