using Dagger.Introspection;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static Dagger.SyntaxTree;
namespace Dagger;

static class API
{
	public static CompilationUnitSyntax Generate(Schema schema, string @namespace)
		=> CompilationUnit()
			.AddComment("This file was auto-generated by Dagger\n// Do not make direct changes to this file.")
			.AddUsings
			(
				"Dagger",
				"System",
				"System.Collections.Generic",
				"System.Collections.Immutable",
				"System.Linq",
				"System.Text.Json",
				"System.Text.Json.Serialization",
				"System.Threading.Tasks"
			)
			.AddUsingStatic("Dagger", "APIUtils")
			.AddMembers
			(
				NamespaceDeclaration(@namespace)
					.AddMembers
					(
						Structures.Generate(schema)
							.Concat(Classes.Generate(schema))
					)
			);
}
